### PR TITLE
Added support for double-precision

### LINKED ISSUE #355: Add support for double-precision
This would add support for builds of Godot that use double-precision floating-point numbers, enabled by building Godot with `precision=double`, as opposed to the default single-precision.

This would allow for much bigger worlds.

### PR DESCRIPTION
**Pull request by mihe**
Fixes #355.

This adds support for building binaries that are compatible with double-precision builds of Godot, which is done by passing `-DGDJ_DOUBLE_PRECISION=TRUE` when generating the build directory.

### CODE REVIEW

**Comment by cridenour** [comment]
Incredible. Already built and tested and works like a dream.

**Comment by mihe** [comment]
That was quick! I haven't tested the physics queries much at all, so if you're using stuff like ray-casts and shape-casts let me know how they're working out for you.

**Comment by cridenour** [comment]
Doing some more testing at 100km from origin:

Raycasts: Work great, both from node and PhysicsServer3D directly.
Shapecasts: Same as above.

That said, CharacterBody3D `move_and_slide` seems to have trouble at this distance. It did fine at 25km which made me believe doubles were working but at 100km the character is unmovable vs. GodotPhysics which shows no difference.

**Comment by mihe** [comment]
Ah, that figures. I should have tested `move_and_slide` before pushing it. I'll fix it shortly.

**Comment by mihe** [comment]
It turned out to be an easy fix, thankfully. (#781)

**Pull request merged**
